/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.util.constant.UseCaseConstants;

/**
 *
 * @author Vladimir Jecić
 */
public class FrmLine extends javax.swing.JDialog {

    /**
     * Creates new form FrmLine
     */
//    public FrmLine(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//    }
    public FrmLine(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scPaneAdd = new javax.swing.JScrollPane();
        panelAdd = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDistance = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        lblTravelTime = new javax.swing.JLabel();
        txtTravelTime = new javax.swing.JTextField();
        lblDeparture = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        cbDeparture = new javax.swing.JComboBox<>();
        cbDestination = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        scPaneStop = new javax.swing.JScrollPane();
        tblStop = new javax.swing.JTable();
        btnAddStop = new javax.swing.JButton();
        btnDeleteStop = new javax.swing.JButton();
        btnEditStop = new javax.swing.JButton();
        btnSaveLine = new javax.swing.JButton();
        panelDetails = new javax.swing.JPanel();
        scPanelDeparture = new javax.swing.JScrollPane();
        tblDeparture = new javax.swing.JTable();
        btnAddDeparture = new javax.swing.JButton();
        btnEditDeparture = new javax.swing.JButton();
        btnDeleteDeparture = new javax.swing.JButton();
        btnAddTicket = new javax.swing.JButton();
        btnDeleteTicket = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        scPaneAdd.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblName.setText("Name:");

        txtName.setToolTipText("");

        lblDistance.setText("Distance(km):");

        lblTravelTime.setText("Expected Travel Time:");

        txtTravelTime.setToolTipText("");

        lblDeparture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeparture.setText("Departure:");

        lblDestination.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDestination.setText("Destination:");

        cbDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblUser.setText("Last Changed by User:");

        scPaneStop.setBorder(javax.swing.BorderFactory.createTitledBorder("Bus Stops"));

        tblStop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scPaneStop.setViewportView(tblStop);

        btnAddStop.setText("Add Stop");

        btnDeleteStop.setText("Delete Stop");

        btnEditStop.setText("Edit Stop");

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(lblDistance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(lblTravelTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTravelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDeparture, 0, 116, Short.MAX_VALUE)
                                    .addComponent(cbDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addComponent(scPaneStop, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDistance))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDeparture)
                            .addComponent(cbDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDestination)
                            .addComponent(cbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtTravelTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTravelTime))))
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scPaneStop, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnAddStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditStop)
                        .addGap(10, 10, 10)
                        .addComponent(btnDeleteStop)))
                .addContainerGap())
        );

        scPaneAdd.setViewportView(panelAdd);

        btnSaveLine.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnSaveLine.setText("Save");

        scPanelDeparture.setBorder(javax.swing.BorderFactory.createTitledBorder("Departures"));

        tblDeparture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scPanelDeparture.setViewportView(tblDeparture);

        btnAddDeparture.setText("Add Departure");

        btnEditDeparture.setText("Edit Departure");

        btnDeleteDeparture.setText("Delete Departure");

        btnAddTicket.setText("Add Ticket");

        btnDeleteTicket.setText("Delete Ticket");

        javax.swing.GroupLayout panelDetailsLayout = new javax.swing.GroupLayout(panelDetails);
        panelDetails.setLayout(panelDetailsLayout);
        panelDetailsLayout.setHorizontalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addComponent(btnAddDeparture)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditDeparture)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteDeparture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnDeleteTicket)
                        .addGap(29, 29, 29))
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addComponent(scPanelDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelDetailsLayout.setVerticalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scPanelDeparture, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDeparture)
                    .addComponent(btnDeleteDeparture)
                    .addComponent(btnAddTicket)
                    .addComponent(btnDeleteTicket)
                    .addComponent(btnEditDeparture))
                .addGap(19, 19, 19))
        );

        btnCancel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(scPaneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(btnSaveLine, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(scPaneAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveLine)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDeparture;
    private javax.swing.JButton btnAddStop;
    private javax.swing.JButton btnAddTicket;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteDeparture;
    private javax.swing.JButton btnDeleteStop;
    private javax.swing.JButton btnDeleteTicket;
    private javax.swing.JButton btnEditDeparture;
    private javax.swing.JButton btnEditStop;
    private javax.swing.JButton btnSaveLine;
    private javax.swing.JComboBox<Object> cbDeparture;
    private javax.swing.JComboBox<Object> cbDestination;
    private javax.swing.JLabel lblDeparture;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTravelTime;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JScrollPane scPaneAdd;
    private javax.swing.JScrollPane scPaneStop;
    private javax.swing.JScrollPane scPanelDeparture;
    private javax.swing.JTable tblDeparture;
    private javax.swing.JTable tblStop;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTravelTime;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    public void addStopActionListener(ActionListener actionListener) {
        btnAddStop.addActionListener(actionListener);
    }

    public void editStopActionListener(ActionListener actionListener) {
        btnEditStop.addActionListener(actionListener);
    }

    public void deleteStopActionListener(ActionListener actionListener) {
        btnDeleteStop.addActionListener(actionListener);
    }

    public void saveLineActionListener(ActionListener actionListener) {
        btnSaveLine.addActionListener(actionListener);
    }

    public void cancelLineActionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }

    public void addDepartureActionListener(ActionListener actionListener) {
        btnAddDeparture.addActionListener(actionListener);
    }

    public void editDepartureActionListener(ActionListener actionListener) {
        btnEditDeparture.addActionListener(actionListener);
    }

    public void deleteDepartureActionListener(ActionListener actionListener) {
        btnDeleteDeparture.addActionListener(actionListener);
    }

    public void addTicketActionListener(ActionListener actionListener) {
        btnAddTicket.addActionListener(actionListener);
    }

    public void deleteTicketActionListener(ActionListener actionListener) {
        btnDeleteTicket.addActionListener(actionListener);
    }

    public void cbDepartureActionListener(ItemListener itemListener) {
        cbDeparture.addItemListener(itemListener);
    }

    public void cbDestinationActionListener(ItemListener itemListener) {
        cbDestination.addItemListener(itemListener);
    }

    public javax.swing.JButton getBtnAddDeparture() {
        return btnAddDeparture;
    }

    public void setBtnAddDeparture(javax.swing.JButton btnAddDeparture) {
        this.btnAddDeparture = btnAddDeparture;
    }

    public javax.swing.JButton getBtnAddStop() {
        return btnAddStop;
    }

    public void setBtnAddStop(javax.swing.JButton btnAddStop) {
        this.btnAddStop = btnAddStop;
    }

    public javax.swing.JButton getBtnAddTicket() {
        return btnAddTicket;
    }

    public void setBtnAddTicket(javax.swing.JButton btnAddTicket) {
        this.btnAddTicket = btnAddTicket;
    }

    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(javax.swing.JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public javax.swing.JButton getBtnDeleteDeparture() {
        return btnDeleteDeparture;
    }

    public void setBtnDeleteDeparture(javax.swing.JButton btnDeleteDeparture) {
        this.btnDeleteDeparture = btnDeleteDeparture;
    }

    public javax.swing.JButton getBtnDeleteStop() {
        return btnDeleteStop;
    }

    public void setBtnDeleteStop(javax.swing.JButton btnDeleteStop) {
        this.btnDeleteStop = btnDeleteStop;
    }

    public javax.swing.JButton getBtnDeleteTicket() {
        return btnDeleteTicket;
    }

    public void setBtnDeleteTicket(javax.swing.JButton btnDeleteTicket) {
        this.btnDeleteTicket = btnDeleteTicket;
    }

    public javax.swing.JButton getBtnEditDeparture() {
        return btnEditDeparture;
    }

    public void setBtnEditDeparture(javax.swing.JButton btnEditDeparture) {
        this.btnEditDeparture = btnEditDeparture;
    }

    public javax.swing.JButton getBtnEditStop() {
        return btnEditStop;
    }

    public void setBtnEditStop(javax.swing.JButton btnEditStop) {
        this.btnEditStop = btnEditStop;
    }

    public javax.swing.JButton getBtnSave() {
        return btnSaveLine;
    }

    public void setBtnSave(javax.swing.JButton btnSave) {
        this.btnSaveLine = btnSave;
    }

    public javax.swing.JComboBox<Object> getCbDeparture() {
        return cbDeparture;
    }

    public void setCbDeparture(javax.swing.JComboBox<Object> cbDeparture) {
        this.cbDeparture = cbDeparture;
    }

    public javax.swing.JComboBox<Object> getCbDestination() {
        return cbDestination;
    }

    public void setCbDestination(javax.swing.JComboBox<Object> cbDestination) {
        this.cbDestination = cbDestination;
    }

    public javax.swing.JLabel getLblDeparture() {
        return lblDeparture;
    }

    public void setLblDeparture(javax.swing.JLabel lblDeparture) {
        this.lblDeparture = lblDeparture;
    }

    public javax.swing.JLabel getLblDestination() {
        return lblDestination;
    }

    public void setLblDestination(javax.swing.JLabel lblDestination) {
        this.lblDestination = lblDestination;
    }

    public javax.swing.JLabel getLblDistance() {
        return lblDistance;
    }

    public void setLblDistance(javax.swing.JLabel lblDistance) {
        this.lblDistance = lblDistance;
    }

    public javax.swing.JLabel getLblName() {
        return lblName;
    }

    public void setLblName(javax.swing.JLabel lblName) {
        this.lblName = lblName;
    }

    public javax.swing.JLabel getLblTravelTime() {
        return lblTravelTime;
    }

    public void setLblTravelTime(javax.swing.JLabel lblTravelTime) {
        this.lblTravelTime = lblTravelTime;
    }

    public javax.swing.JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(javax.swing.JLabel lblUser) {
        this.lblUser = lblUser;
    }

    public javax.swing.JPanel getPanelDetails() {
        return panelDetails;
    }

    public void setPanelDetails(javax.swing.JPanel panelDetails) {
        this.panelDetails = panelDetails;
    }

    public javax.swing.JTable getTblDeparture() {
        return tblDeparture;
    }

    public void setTblDeparture(javax.swing.JTable tblDeparture) {
        this.tblDeparture = tblDeparture;
    }

    public javax.swing.JTable getTblStop() {
        return tblStop;
    }

    public void setTblStop(javax.swing.JTable tblStop) {
        this.tblStop = tblStop;
    }

    public javax.swing.JTextField getTxtDistance() {
        return txtDistance;
    }

    public void setTxtDistance(javax.swing.JTextField txtDistance) {
        this.txtDistance = txtDistance;
    }

    public javax.swing.JTextField getTxtName() {
        return txtName;
    }

    public void setTxtName(javax.swing.JTextField txtName) {
        this.txtName = txtName;
    }

    public javax.swing.JTextField getTxtTravelTime() {
        return txtTravelTime;
    }

    public void setTxtTravelTime(javax.swing.JTextField txtTravelTime) {
        this.txtTravelTime = txtTravelTime;
    }

    public javax.swing.JTextField getTxtUser() {
        return txtUser;
    }

    public void setTxtUser(javax.swing.JTextField txtUser) {
        this.txtUser = txtUser;
    }

}
