/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Vladimir Jecić
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblLogo = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        jmBarMain = new javax.swing.JMenuBar();
        jmenuStation = new javax.swing.JMenu();
        jmiStationNew = new javax.swing.JMenuItem();
        jmiStationDelete = new javax.swing.JMenuItem();
        jmenuLine = new javax.swing.JMenu();
        jmiLineNew = new javax.swing.JMenuItem();
        jmiLineEdit = new javax.swing.JMenuItem();
        jmiLineDelete = new javax.swing.JMenuItem();
        jmenuDeparture = new javax.swing.JMenu();
        jmiDepartureNew = new javax.swing.JMenuItem();
        jmiDepartureDelete = new javax.swing.JMenuItem();
        jmenuTicket = new javax.swing.JMenu();
        jmiTicketNew = new javax.swing.JMenuItem();
        jmiTicketDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(160, 160, 246));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");

        jDesktopPane1.setLayer(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnLogOut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnHelp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmenuStation.setText("Station");

        jmiStationNew.setText("New");
        jmenuStation.add(jmiStationNew);

        jmiStationDelete.setText("Delete");
        jmenuStation.add(jmiStationDelete);

        jmBarMain.add(jmenuStation);

        jmenuLine.setText("Line");

        jmiLineNew.setText("New");
        jmenuLine.add(jmiLineNew);

        jmiLineEdit.setText("Edit");
        jmenuLine.add(jmiLineEdit);

        jmiLineDelete.setText("Delete");
        jmenuLine.add(jmiLineDelete);

        jmBarMain.add(jmenuLine);

        jmenuDeparture.setText("Departure");

        jmiDepartureNew.setText("New");
        jmenuDeparture.add(jmiDepartureNew);

        jmiDepartureDelete.setText("Delete");
        jmenuDeparture.add(jmiDepartureDelete);

        jmBarMain.add(jmenuDeparture);

        jmenuTicket.setText("Ticket");

        jmiTicketNew.setText("New");
        jmenuTicket.add(jmiTicketNew);

        jmiTicketDelete.setText("Delete");
        jmenuTicket.add(jmiTicketDelete);

        jmBarMain.add(jmenuTicket);

        setJMenuBar(jmBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jmBarMain;
    private javax.swing.JMenu jmenuDeparture;
    private javax.swing.JMenu jmenuLine;
    private javax.swing.JMenu jmenuStation;
    private javax.swing.JMenu jmenuTicket;
    private javax.swing.JMenuItem jmiDepartureDelete;
    private javax.swing.JMenuItem jmiDepartureNew;
    private javax.swing.JMenuItem jmiLineDelete;
    private javax.swing.JMenuItem jmiLineEdit;
    private javax.swing.JMenuItem jmiLineNew;
    private javax.swing.JMenuItem jmiStationDelete;
    private javax.swing.JMenuItem jmiStationNew;
    private javax.swing.JMenuItem jmiTicketDelete;
    private javax.swing.JMenuItem jmiTicketNew;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
    public void jmiStationNewActionListener(ActionListener al){
        jmiStationNew.addActionListener(al);
    }
    public void jmiStationDeleteActionListener(ActionListener al){
        jmiStationDelete.addActionListener(al);
    }
    public void jmiLineNewActionListener(ActionListener al){
        jmiLineNew.addActionListener(al);
    }
    public void jmiLineEditActionListener(ActionListener al){
        jmiLineEdit.addActionListener(al);
    }
    public void jmiLineDeleteActionListener(ActionListener al){
        jmiLineDelete.addActionListener(al);
    }
    public void jmiDepartureNewActionListener(ActionListener al){
        jmiDepartureNew.addActionListener(al);
    }
    public void jmiDepartureDeleteActionListener(ActionListener al){
        jmiDepartureDelete.addActionListener(al);
    }
    public void jmiTicketNewActionListener(ActionListener al){
        jmiTicketNew.addActionListener(al);
    }
    public void jmiTicketDeleteActionListener(ActionListener al){
        jmiTicketDelete.addActionListener(al);
    }
    public void btnLogOutActionListener(ActionListener al){
        btnLogOut.addActionListener(al);
    }                 
    public void btnHelpActionListener(ActionListener al){
        btnHelp.addActionListener(al);
    }                 
    
    public javax.swing.JButton getBtnLogOut() {
        return btnLogOut;
    }
    public void setBtnLogOut(javax.swing.JButton btnLogOut) {
        this.btnLogOut = btnLogOut;
    }
    public javax.swing.JLabel getLblLogo() {
        return lblLogo;
    }
    public void setLblLogo(javax.swing.JLabel lblLogo) {
        this.lblLogo = lblLogo;
    }
    public javax.swing.JMenuItem getMiChangeLine() {
        return jmiLineEdit;
    }
    public void setMiChangeLine(javax.swing.JMenuItem miChangeLine) {
        this.jmiLineEdit = miChangeLine;
    }
    public javax.swing.JMenuItem getMiDeleteDeparture() {
        return jmiDepartureDelete;
    }
    public void setMiDeleteDeparture(javax.swing.JMenuItem miDeleteDeparture) {
        this.jmiDepartureDelete = miDeleteDeparture;
    }
    public javax.swing.JMenuItem getMiDeleteLine() {
        return jmiLineDelete;
    }
    public void setMiDeleteLine(javax.swing.JMenuItem miDeleteLine) {
        this.jmiLineDelete = miDeleteLine;
    }
    public javax.swing.JMenuItem getMiDeleteStation() {
        return jmiStationDelete;
    }
    public void setMiDeleteStation(javax.swing.JMenuItem miDeleteStation) {
        this.jmiStationDelete = miDeleteStation;
    }
    public javax.swing.JMenuItem getMiDeleteTicket() {
        return jmiTicketDelete;
    }
    public void setMiDeleteTicket(javax.swing.JMenuItem miDeleteTicket) {
        this.jmiTicketDelete = miDeleteTicket;
    }
    public javax.swing.JMenuItem getMiNewDeparture() {
        return jmiDepartureNew;
    }
    public void setMiNewDeparture(javax.swing.JMenuItem miNewDeparture) {
        this.jmiDepartureNew = miNewDeparture;
    }
    public javax.swing.JMenuItem getMiNewLine() {
        return jmiLineNew;
    }
    public void setMiNewLine(javax.swing.JMenuItem miNewLine) {
        this.jmiLineNew = miNewLine;
    }
    public javax.swing.JMenuItem getMiNewStation() {
        return jmiStationNew;
    }
    public void setMiNewStation(javax.swing.JMenuItem miNewStation) {
        this.jmiStationNew = miNewStation;
    }
    public javax.swing.JMenuItem getMiNewTicket() {
        return jmiTicketNew;
    }
    public void setMiNewTicket(javax.swing.JMenuItem miNewTicket) {
        this.jmiTicketNew = miNewTicket;

    }

    

}
