/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Vladimir Jecić
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain(){
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        jmbarMain = new javax.swing.JMenuBar();
        jmenuServer = new javax.swing.JMenu();
        jmiStartServer = new javax.swing.JMenuItem();
        jmiStopServer = new javax.swing.JMenuItem();
        jmenuConfiguration = new javax.swing.JMenu();
        jmiServerConfiguration = new javax.swing.JMenuItem();
        jmiDatabaseConfiguration = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClient);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStatus.setText("Status: stopped");

        jmenuServer.setText("Server");

        jmiStartServer.setText("Start");
        jmiStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStartServerActionPerformed(evt);
            }
        });
        jmenuServer.add(jmiStartServer);

        jmiStopServer.setText("Stop");
        jmenuServer.add(jmiStopServer);

        jmbarMain.add(jmenuServer);

        jmenuConfiguration.setText("Configuration");

        jmiServerConfiguration.setText("Server");
        jmenuConfiguration.add(jmiServerConfiguration);

        jmiDatabaseConfiguration.setText("Database");
        jmenuConfiguration.add(jmiDatabaseConfiguration);

        jmbarMain.add(jmenuConfiguration);

        setJMenuBar(jmbarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStartServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiStartServerActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar jmbarMain;
    private javax.swing.JMenu jmenuConfiguration;
    private javax.swing.JMenu jmenuServer;
    private javax.swing.JMenuItem jmiDatabaseConfiguration;
    private javax.swing.JMenuItem jmiServerConfiguration;
    private javax.swing.JMenuItem jmiStartServer;
    private javax.swing.JMenuItem jmiStopServer;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblClient;
    // End of variables declaration//GEN-END:variables
    public void jmiStartServerActionListener(ActionListener actionListener){
        jmiStartServer.addActionListener(actionListener);
    }
    public void jmiStopServerActionListener(ActionListener actionListener){
        jmiStopServer.addActionListener(actionListener);
    }
    public void jmiDatabaseConfiguration(ActionListener actionListener){
        jmiDatabaseConfiguration.addActionListener(actionListener);
    }
    public void jmiServerConfiguration(ActionListener actionListener){
        jmiServerConfiguration.addActionListener(actionListener);
    }

    public javax.swing.JTable getTblClient() {
        return tblClient;
    }

    public javax.swing.JLabel getLblStatus() {
        return lblStatus;
    }
    public javax.swing.JMenuItem getJmiStartServer() {
        return jmiStartServer;
    }


    public javax.swing.JMenuItem getJmiStopServer() {
        return jmiStopServer;
    }


    public javax.swing.JMenuItem getJmiDatabaseConfiguration() {
        return jmiDatabaseConfiguration;
    }

    public javax.swing.JMenuItem getJmiServerConfiguration() {
        return jmiServerConfiguration;
    }


}
